config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :buildings do
    resources :apartments
  end

  # Otras rutas...
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building

  validates :number, uniqueness: { scope: :building_id, message: 'ya existe en este edificio' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :apartments

  end
  

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/apartments_controller.rb
# app/controllers/apartments_controller.rb

class ApartmentsController < ApplicationController
    before_action :set_building
    before_action :set_apartment, only: [:show]
  
    def index
      @apartments = @building.apartments
    end
  
    def show
    end
  
    def new
      @apartment = @building.apartments.build
    end
  
    def create
      @apartment = @building.apartments.build(apartment_params)
      if @apartment.save
        redirect_to building_path(@building), notice: 'Departamento creado exitosamente.'
      else
        render :new
      end
    end
  
    private
  
    def set_building
      @building = Building.find(params[:building_id])
    end
  
    def set_apartment
      @apartment = @building.apartments.find(params[:id])
    end
  
    def apartment_params
      params.require(:apartment).permit(:number)
    end
  end
  

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
  end
  

app/controllers/buildings_controller.rb
# app/controllers/buildings_controller.rb

class BuildingsController < ApplicationController
    before_action :set_building, only: [:show]
  
    def index
      @buildings = Building.all
    end
  
    def show
      @apartments = @building.apartments
    end
  
    def new
      @building = Building.new
    end
  
    def create
      @building = Building.new(building_params)
      if @building.save
        redirect_to buildings_path, notice: 'Edificio creado exitosamente.'
      else
        render :new
      end
    end
  
    private
  
    def set_building
      @building = Building.find(params[:id])
    end
  
    def building_params
      params.require(:building).permit(:name, :address, :city)
    end
  end
  

app/controllers/welcome_controller.rb
# app/controllers/welcome_controller.rb

class WelcomeController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index]
  
    def index
      @buildings = Building.all
      @apartments = Apartment.all
    end
  end
  

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/apartments/_form.html.erb
<!-- app/views/apartments/_form.html.erb -->

<%= form_with(model: [@building, @apartment], url: building_apartments_path(@building), method: :post) do |form| %>
  <div>
    <%= form.label :number, 'Número' %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.submit 'Guardar' %>
  </div>
<% end %>

app/views/apartments/index.html.erb
<!-- app/views/apartments/index.html.erb -->

<h1>Lista de Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Número</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.number %></td>
        <td>
          <%= link_to 'Ver Detalles', building_apartment_path(@building, apartment) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nuevo Departamento', new_building_apartment_path(@building) %>

app/views/apartments/new.html.erb
<!-- app/views/apartments/new.html.erb -->

<h1>Nuevo Departamento</h1>

<%= render 'form' %>

<%= link_to 'Volver a la Lista de Departamentos', building_apartments_path(@building) %>

app/views/apartments/show.html.erb
<!-- app/views/apartments/show.html.erb -->

<h1>Detalles del Departamento</h1>

<p><strong>Número:</strong> <%= @apartment.number %></p>

<%= link_to 'Volver a la Lista de Departamentos', building_apartments_path(@building) %>

app/views/buildings/_form.html.erb
<!-- app/views/buildings/_form.html.erb -->

<%= form_with(model: @building, url: buildings_path, method: :post) do |form| %>
  <div>
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, 'Dirección' %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city, 'Ciudad' %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.submit 'Guardar' %>
  </div>
<% end %>

app/views/buildings/index.html.erb
<!-- app/views/buildings/index.html.erb -->

<h1>Lista de Edificios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Dirección</th>
      <th>Ciudad</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.name %></td>
        <td><%= building.address %></td>
        <td><%= building.city %></td>
        <td>
          <%= link_to 'Ver Detalles', building_path(building) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nuevo Edificio', new_building_path %>

app/views/buildings/new.html.erb
<!-- app/views/buildings/new.html.erb -->

<h1>Nuevo Edificio</h1>

<%= render 'form' %>

<%= link_to 'Volver a la Lista de Edificios', buildings_path %>

app/views/buildings/show.html.erb
<!-- app/views/buildings/show.html.erb -->

<h1>Detalles del Edificio</h1>

<p><strong>Nombre:</strong> <%= @building.name %></p>
<p><strong>Dirección:</strong> <%= @building.address %></p>
<p><strong>Ciudad:</strong> <%= @building.city %></p>

<h2>Departamentos</h2>
<ul>
  <% @apartments.each do |apartment| %>
    <li>Número: <%= apartment.number %></li>
  <% end %>
</ul>

<%= link_to 'Volver a la Lista de Edificios', buildings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tu Aplicación</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Agregar  -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <!-- Barra de navegación -->
  <nav>
    <!-- Aquí -->
    <% if user_signed_in? %>
      <p>Bienvenido, <%= current_user.nombre %> <%= current_user.apellido %></p>
    <% end %>
  </nav>

  <!-- Contenido principal de la página -->
  <div class="container">
    <%= yield %>
  </div>

  <!-- Pie de página -->
  <footer>
    <!-- Agrega  -->
  </footer>

  <!-- Scripts JavaScript -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/welcome/index.html.erb
<!-- app/views/welcome/index.html.erb -->

<h1>Bienvenido a la Corredora de Propiedades</h1>

<h2>Edificios</h2>
<ul>
  <% @buildings.each do |building| %>
    <li><%= building.name %> - <%= building.address %> - <%= building.city %></li>
  <% end %>
</ul>

<h2>Departamentos</h2>
<ul>
  <% @apartments.each do |apartment| %>
    <li>Edificio: <%= apartment.building.name %> - Número: <%= apartment.number %></li>
  <% end %>
</ul>